---
title: "Lectura SMN"
author: "Viacheslav Shalsiko"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
## En lugar del número de estado 00 especificar un valor de 01 hasta 32
state <- "00"
```


```{r}
library(sp)
library(sf)
```


```{r}
pattern = paste0("^dia", state, ".*\\.txt$")
files <- list.files(path = "./Base", pattern = pattern)
files
```


```{r}
reader_day_table <- function (name, skip) {
  data <- read.delim(paste0("./Base/",files[i]), 
                     skip=skip,
                     header=FALSE,
                     na.strings = "NULO")
  data_colnames <- c("FECHA","PREC","EVAP","TMAX","TMIN")
  names(data) <- data_colnames
  data$FECHA <- as.Date(data$FECHA,'%Y-%m-%d')
  return(data)
}

reader_day_table_header <- function (name) {
  f = readLines(name)
  ## determinar numero de linea de cada grupo de datos de interes
  ln_estacion <- grep("^\\s*ESTACIÓN\\s*:", f)
  ln_nombre <- grep("^\\s*NOMBRE\\s*:", f)
  ln_situacion <- grep("^\\s*SITUACIÓN\\s*:", f)
  ln_cveomm <- grep("^\\s*CVE-OMM\\s*:", f) 
  ln_latitud <- grep("^\\s*LATITUD\\s*:", f)
  ln_longitud <- grep("^\\s*LONGITUD\\s*:", f)
  ln_altitud <- grep("^\\s*ALTITUD\\s*:", f)
  ln_datos <- grep("^FECHA\\s*PRECIP\\s*EVAP\\s*TMAX\\s*TMIN", f)
  
  ## buscar los valores de interes en las lineas seleccionadas
  estacion <- sub("(^\\s*ESTACIÓN\\s*:\\s*)([0-9]+)(\\s*$)", "\\2", f[ln_estacion],perl=TRUE)
  nombre <- sub("(^\\s*NOMBRE\\s*:\\s*)([A-ZÁÓÚÉÍÑ0-9(). ]+?)(\\s*$)", "\\2", f[ln_nombre],perl=TRUE)
  situacion <- sub("(^\\s*SITUACIÓN\\s*:\\s*)([A-Z]+?)(\\s*$)", "\\2", f[ln_situacion],perl=TRUE)
  cveomm <- sub("(^\\s*CVE-OMM\\s*:\\s*)([0-9]*)(\\s*$)", "\\2", f[ln_cveomm],perl=TRUE)
  latitud <- sub("(^\\s*LATITUD\\s*:\\s*)([0-9-.]*)(\\s*°\\s*$)", "\\2", f[ln_latitud],perl=TRUE)
  longitud <- sub("(^\\s*LONGITUD\\s*:\\s*)([0-9-.]*)(\\s*°\\s*$)", "\\2", f[ln_longitud],perl=TRUE)
  altitud <- sub("(^\\s*ALTITUD\\s*:\\s*)([0-9-.]*)(\\s*msnm\\s*$)", "\\2", f[ln_altitud],perl=TRUE)
  
  ## colocar resultados en una lista
  resultado <- list()
  resultado$datos <- as.numeric(ln_datos)
  resultado$estacion <- estacion
  resultado$nombre <- nombre
  resultado$situacion <- situacion
  resultado$cveomm <- cveomm
  resultado$latitud <- as.numeric(latitud)
  resultado$longitud <- as.numeric(longitud)
  resultado$altitud <- as.numeric(altitud)

  ## estraer tabla de datos y agregar a la estructura de datos
  datos <- reader_day_table(name, as.numeric(ln_datos) + 1)
  resultado$datos <- datos
    
  resultado
}
```

```{r}
## estructura de datos para almacenar conjunto de puntos de estaciones SMN
smn_points_df <- data.frame(latitud=numeric(),
                            longitud=numeric(),
                            altitud=numeric(),
                            estacion=numeric(),
                            nombre=character())

## estructura de datos para almacenar lecturas diarias en todas estaciones SMN
smn_data_df <- data.frame(ESTACION=numeric(),
                          FECHA=as.Date(character()),
                          PREC=numeric(),
                          EVAP=numeric(),
                          TMAX=numeric(),
                          TMIN=numeric())

## llenar las estructuras de datos de puntos y de lecturas diarias
for (i in 1:length(files)) {
#for (i in 1:10) {
  ## leer archivo de datos
  file_name <- paste0("./Base/",files[i])
  header <- reader_day_table_header(file_name)
  print(paste("Procesando:",as.character(header$estacion),"-",as.character(header$nombre)))
  print(dim(header$datos))
  
  ## agregar linea con info sobre el punto
  smn_points_df <- rbind(smn_points_df,
                      data.frame(latitud=as.numeric(header$latitud),
                                 longitud=as.numeric(header$longitud),
                                 altitud=as.numeric(header$altitud),
                                 estacion=as.numeric(header$estacion),
                                 nombre=as.character(header$nombre)))
  ## agregar el segmento de registros
  data_fragment <- cbind(data.frame(
                         ESTACION=rep(as.numeric(header$estacion),dim(header$datos)[1])),
                         header$datos)
  smn_data_df <- rbind(smn_data_df,
                       data_fragment)
}
```


```{r}
smn_data_df$A <- format(smn_data_df$FECHA,"%Y")
smn_data_df$M <- format(smn_data_df$FECHA,"%m")
smn_data_df$D <- format(smn_data_df$FECHA,"%j")
dim(smn_data_df)
head(smn_data_df)
str(smn_data_df)
```

```{r}
name_csv <- paste0("smn_", state, "_datos_diarios.csv")
write.csv(smn_data_df, name_csv, row.names = FALSE)
```


```{r}
knitr::kable(smn_points_df)

myCRS=CRS("+init=epsg:4326")
smn_points <- SpatialPointsDataFrame(coords=smn_points_df[,c("longitud","latitud")],
                                     data=smn_points_df, proj4string=myCRS)
```

```{r}
plot(smn_points)
```

```{r}
smn_points_sf <- sf::st_as_sf(smn_points, coords = c("x","y"))
name_shape <- paste0("smn_", state, "_puntos.shp")
st_write(smn_points_sf, name_shape)
```


